// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAba4cZu7GjuIhp8xmIPO7GE8Vxd-bIrBk',
    appId: '1:214561293210:web:912c6d0da457cde845b023',
    messagingSenderId: '214561293210',
    projectId: 'kerjain-224e2',
    authDomain: 'kerjain-224e2.firebaseapp.com',
    storageBucket: 'kerjain-224e2.firebasestorage.app',
    measurementId: 'G-PYB5L2WSVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZkPElLGq9dHPM2QcGIZ6L_-iPEiuT2Pw',
    appId: '1:214561293210:android:9eeca67e5fb95fc345b023',
    messagingSenderId: '214561293210',
    projectId: 'kerjain-224e2',
    storageBucket: 'kerjain-224e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC2Iu6e5OBeoplw5xzmXiarAZ6sfWNols',
    appId: '1:214561293210:ios:2f4d98e345063b8445b023',
    messagingSenderId: '214561293210',
    projectId: 'kerjain-224e2',
    storageBucket: 'kerjain-224e2.firebasestorage.app',
    iosBundleId: 'com.example.homeHub',
  );
}
